# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_openpay', '0003_auto_20160805_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='cancel_at_end_period',
            new_name='cancel_at_period_end',
        ),
    ]
