# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_openpay', '0004_auto_20160806_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='code',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='code',
        ),
        migrations.AddField(
            model_name='address',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AddField(
            model_name='card',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.CharField(blank=True, choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=8, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='charge',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='openpay_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenPay ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(blank=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='creation_date',
            field=models.DateTimeField(blank=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='method',
            field=models.CharField(blank=True, choices=[('card', 'Card')], default='card', max_length=15, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creation_date',
            field=models.DateTimeField(blank=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='The telephone number can only contain digits.  The maximum number of digits is 15.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='creation_date',
            field=models.DateTimeField(blank=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='creation_date',
            field=models.DateTimeField(blank=True, verbose_name='Creation date'),
        ),
    ]
