from . import _ug

address_countrycodes = (  # FIXME: Translate from spanish to english
    ('AF', _ug('Afganistán')),
    ('AL', _ug('Albania')),
    ('DE', _ug('Alemania')),
    ('AD', _ug('Andorra')),
    ('AO', _ug('Angola')),
    ('AI', _ug('Anguila')),
    ('AG', _ug('Antigua y Barbuda')),
    ('AN', _ug('Antillas Holandesas')),
    ('AQ', _ug('Antártida')),
    ('SA', _ug('Arabia Saudita')),
    ('DZ', _ug('Argelia')),
    ('AR', _ug('Argentina')),
    ('AM', _ug('Armenia')),
    ('AW', _ug('Aruba')),
    ('AU', _ug('Australia')),
    ('AT', _ug('Austria')),
    ('AZ', _ug('Azerbaiyán')),
    ('BS', _ug('Bahamas')),
    ('BH', _ug('Bahráin')),
    ('BD', _ug('Bangladesh')),
    ('BB', _ug('Barbados')),
    ('BZ', _ug('Belice')),
    ('BJ', _ug('Benín')),
    ('BM', _ug('Bermudas')),
    ('BY', _ug('Bielorrusia')),
    ('BO', _ug('Bolivia')),
    ('BQ', _ug('Bonaire, San Eustaquio y Saba')),
    ('BA', _ug('Bosnia y Hercegovina')),
    ('BW', _ug('Botsuana')),
    ('BR', _ug('Brasil')),
    ('BN', _ug('Brunéi')),
    ('BG', _ug('Bulgaria')),
    ('BF', _ug('Burkina Faso')),
    ('BI', _ug('Burundi')),
    ('BT', _ug('Bután')),
    ('BE', _ug('Bélgica')),
    ('CV', _ug('Cabo Verde')),
    ('KH', _ug('Camboya')),
    ('CM', _ug('Camerún')),
    ('CA', _ug('Canadá')),
    ('TD', _ug('Chad')),
    ('CZ', _ug('Chequia')),
    ('CL', _ug('Chile')),
    ('CN', _ug('China')),
    ('CY', _ug('Chipre')),
    ('VA', _ug('Ciudad del Vaticano')),
    ('CO', _ug('Colombia')),
    ('KM', _ug('Comores')),
    ('CG', _ug('Congo')),
    ('KP', _ug('Corea del Norte')),
    ('KR', _ug('Corea del Sur')),
    ('CR', _ug('Costa Rica')),
    ('CI', _ug('Costa de Marfil')),
    ('HR', _ug('Croacia')),
    ('CU', _ug('Cuba')),
    ('CW', _ug('Curaçao')),
    ('DK', _ug('Dinamarca')),
    ('DM', _ug('Dominica')),
    ('EC', _ug('Ecuador')),
    ('EG', _ug('Egipto')),
    ('SV', _ug('El Salvador')),
    ('AE', _ug('Emiratos Árabes Unidos')),
    ('ER', _ug('Eritrea')),
    ('SK', _ug('Eslovaquia')),
    ('SI', _ug('Eslovenia')),
    ('ES', _ug('España')),
    ('US', _ug('Estados Unidos')),
    ('EE', _ug('Estonia')),
    ('ET', _ug('Etiopía')),
    ('PH', _ug('Filipinas')),
    ('FI', _ug('Finlandia')),
    ('FJ', _ug('Fiyi')),
    ('FR', _ug('Francia')),
    ('GA', _ug('Gabón')),
    ('GM', _ug('Gambia')),
    ('GE', _ug('Georgia')),
    ('GH', _ug('Ghana')),
    ('GI', _ug('Gibraltar')),
    ('GD', _ug('Granada')),
    ('GR', _ug('Grecia')),
    ('GL', _ug('Groenlandia')),
    ('GP', _ug('Guadalupe')),
    ('GU', _ug('Guam')),
    ('GT', _ug('Guatemala')),
    ('GF', _ug('Guayana Francesa')),
    ('GG', _ug('Guernsey')),
    ('GN', _ug('Guinea')),
    ('GQ', _ug('Guinea Ecuatorial')),
    ('GW', _ug('Guinea-Bissau')),
    ('GY', _ug('Guyana')),
    ('HT', _ug('Haití')),
    ('NL', _ug('Holanda')),
    ('HN', _ug('Honduras')),
    ('HK', _ug('Hong Kong')),
    ('HU', _ug('Hungría')),
    ('IN', _ug('India')),
    ('ID', _ug('Indonesia')),
    ('IQ', _ug('Iraq')),
    ('IE', _ug('Irlanda')),
    ('IR', _ug('Irán')),
    ('BV', _ug('Isla Bouvet')),
    ('CX', _ug('Isla Christmas')),
    ('NF', _ug('Isla Norfolk')),
    ('IM', _ug('Isla de Man')),
    ('IS', _ug('Islandia')),
    ('AX', _ug('Islas Aland')),
    ('KY', _ug('Islas Caimán')),
    ('CC', _ug('Islas Cocos')),
    ('CK', _ug('Islas Cook')),
    ('FO', _ug('Islas Feroe')),
    ('GS', _ug('Islas Georgia del Sur y Sandwich del Sur')),
    ('HM', _ug('Islas Heard y McDonald')),
    ('FK', _ug('Islas Malvinas')),
    ('MP', _ug('Islas Marianas del Norte')),
    ('MH', _ug('Islas Marshall')),
    ('PN', _ug('Islas Pitcairn')),
    ('SB', _ug('Islas Salomón')),
    ('TC', _ug('Islas Turcas y Caicos')),
    ('VI', _ug('Islas Vírgenes Americanas')),
    ('VG', _ug('Islas Vírgenes Británicas')),
    ('UM', _ug('Islas menores alejadas de los Estados Unidos')),
    ('IL', _ug('Israel')),
    ('IT', _ug('Italia')),
    ('JM', _ug('Jamaica')),
    ('JP', _ug('Japón')),
    ('JE', _ug('Jersey')),
    ('JO', _ug('Jordania')),
    ('KZ', _ug('Kazajstán')),
    ('KE', _ug('Kenia')),
    ('KG', _ug('Kirguizistán')),
    ('KI', _ug('Kiribati')),
    ('KW', _ug('Kuwait')),
    ('LA', _ug('Laos')),
    ('LS', _ug('Lesoto')),
    ('LV', _ug('Letonia')),
    ('LR', _ug('Liberia')),
    ('LY', _ug('Libia')),
    ('LI', _ug('Liechtenstein')),
    ('LT', _ug('Lituania')),
    ('LU', _ug('Luxemburgo')),
    ('LB', _ug('Líbano')),
    ('MO', _ug('Macao')),
    ('MK', _ug('Macedonia')),
    ('MG', _ug('Madagascar')),
    ('MY', _ug('Malasia')),
    ('MW', _ug('Malaui')),
    ('MV', _ug('Maldivas')),
    ('MT', _ug('Malta')),
    ('ML', _ug('Malí')),
    ('MA', _ug('Marruecos')),
    ('MQ', _ug('Martinica')),
    ('MU', _ug('Mauricio')),
    ('MR', _ug('Mauritania')),
    ('YT', _ug('Mayotte')),
    ('FM', _ug('Micronesia')),
    ('MD', _ug('Moldavia')),
    ('MN', _ug('Mongolia')),
    ('ME', _ug('Montenegro')),
    ('MS', _ug('Montserrat')),
    ('MZ', _ug('Mozambique')),
    ('MM', _ug('Myanmar')),
    ('MX', _ug('México')),
    ('MC', _ug('Mónaco')),
    ('NA', _ug('Namibia')),
    ('NR', _ug('Nauru')),
    ('NP', _ug('Nepal')),
    ('NI', _ug('Nicaragua')),
    ('NG', _ug('Nigeria')),
    ('NU', _ug('Niue')),
    ('NO', _ug('Noruega')),
    ('NC', _ug('Nueva Caledonia')),
    ('NZ', _ug('Nueva Zelanda')),
    ('NE', _ug('Níger')),
    ('OM', _ug('Omán')),
    ('PW', _ug('Palaos')),
    ('PS', _ug('Palestina')),
    ('PA', _ug('Panamá')),
    ('PG', _ug('Papúa New Guinea')),
    ('PK', _ug('Paquistán')),
    ('PY', _ug('Paraguay')),
    ('PE', _ug('Perú')),
    ('PF', _ug('Polinesia Francesa')),
    ('PL', _ug('Polonia')),
    ('PT', _ug('Portugal')),
    ('PR', _ug('Puerto Rico')),
    ('QA', _ug('Qatar')),
    ('GB', _ug('Reino Unido')),
    ('CF', _ug('República Centroafricana')),
    ('CD', _ug('República Democrática del Congo')),
    ('DO', _ug('República Dominicana')),
    ('RE', _ug('Reunión')),
    ('RW', _ug('Ruanda')),
    ('RO', _ug('Rumania')),
    ('RU', _ug('Rusia')),
    ('EH', _ug('Sahara Occidental')),
    ('WS', _ug('Samoa')),
    ('AS', _ug('Samoa Americana')),
    ('BL', _ug('San Bartolomé')),
    ('KN', _ug('San Cristóbal y Nieves')),
    ('SM', _ug('San Marino')),
    ('MF', _ug('San Martín')),
    ('SX', _ug('San Martín (región holandesa)')),
    ('PM', _ug('San Pedro y Miquelón')),
    ('VC', _ug('San Vicente y las Granadinas')),
    ('SH', _ug('Santa Helena')),
    ('LC', _ug('Santa Lucia')),
    ('ST', _ug('Santo Tomé y Príncipe')),
    ('SN', _ug('Senegal')),
    ('RS', _ug('Serbia')),
    ('SC', _ug('Seychelles')),
    ('SL', _ug('Sierra Leona')),
    ('SG', _ug('Singapur')),
    ('SY', _ug('Siria')),
    ('SO', _ug('Somalia')),
    ('LK', _ug('Sri Lanka')),
    ('SZ', _ug('Suazilandia')),
    ('ZA', _ug('Sudáfrica')),
    ('SD', _ug('Sudán')),
    ('SS', _ug('Sudán del Sur')),
    ('SE', _ug('Suecia')),
    ('CH', _ug('Suiza')),
    ('SR', _ug('Surinam')),
    ('SJ', _ug('Svalbard y Jan Mayen')),
    ('TH', _ug('Tailandia')),
    ('TW', _ug('Taiwán')),
    ('TZ', _ug('Tanzania')),
    ('TJ', _ug('Tayikistán')),
    ('IO', _ug('Territorio Británico del Océano Índico')),
    ('TF', _ug('Territorios Franceses del Sur')),
    ('TL', _ug('Timor Oriental')),
    ('TG', _ug('Togo')),
    ('TK', _ug('Tokelau')),
    ('TO', _ug('Tonga')),
    ('TT', _ug('Trinidad y Tobago')),
    ('TM', _ug('Turkmenistán')),
    ('TR', _ug('Turquía')),
    ('TV', _ug('Tuvalu')),
    ('TN', _ug('Túnez')),
    ('UA', _ug('Ucrania')),
    ('UG', _ug('Uganda')),
    ('UY', _ug('Uruguay')),
    ('UZ', _ug('Uzbekistán')),
    ('VU', _ug('Vanuatu')),
    ('VE', _ug('Venezuela')),
    ('VN', _ug('Vietnam')),
    ('WF', _ug('Wallis y Futuna')),
    ('YE', _ug('Yemen')),
    ('DJ', _ug('Yibuti')),
    ('ZM', _ug('Zambia')),
    ('ZW', _ug('Zimbabue')),
)

plan_statusafter_unpaid = 'unpaid'
plan_statusafter_cancelled = 'cancelled'
plan_statusafter = (
    (plan_statusafter_unpaid, _ug('Unpaid')),
    (plan_statusafter_cancelled, _ug('Cancelled')),
)

plan_repeatunit_week = 'week'
plan_repeatunit_month = 'month'
plan_repeatunit_year = 'year'
plan_repeatunit = (
    (plan_repeatunit_week, _ug('Week')),
    (plan_repeatunit_month, _ug('Month')),
    (plan_repeatunit_year, _ug('Year')),
)
