def verification(body):
    print(body['id'])
    print(body['verification_code'])


def chargeRefunded(body):
    print(body['transaction']['id'])
    print(body['transaction']['authorization'])
    print(body['transaction']['method'])
    print(body['transaction']['operation_type'])
    print(body['transaction']['transaction_type'])
    print(body['transaction']['status'])
    print(body['transaction']['conciliated'])
    print(body['transaction']['creation_date'])
    print(body['transaction']['operation_date'])
    print(body['transaction']['description'])
    print(body['transaction']['error_message'])
    print(body['transaction']['order_id'])
    print(body['transaction']['customer_id'])
    print(body['transaction']['amount'])
    print(body['transaction']['currency'])


def chargeCancelled(body):
    print(body['transaction']['id'])
    print(body['transaction']['authorization'])
    print(body['transaction']['method'])
    print(body['transaction']['operation_type'])
    print(body['transaction']['transaction_type'])
    print(body['transaction']['status'])
    print(body['transaction']['conciliated'])
    print(body['transaction']['creation_date'])
    print(body['transaction']['operation_date'])
    print(body['transaction']['description'])
    print(body['transaction']['error_message'])
    print(body['transaction']['order_id'])
    print(body['transaction']['customer_id'])
    print(body['transaction']['amount'])
    print(body['transaction']['currency'])


def chargeCreated(body):
    print(body['transaction']['id'])
    print(body['transaction']['authorization'])
    print(body['transaction']['method'])
    print(body['transaction']['operation_type'])
    print(body['transaction']['transaction_type'])
    print(body['transaction']['status'])
    print(body['transaction']['conciliated'])
    print(body['transaction']['creation_date'])
    print(body['transaction']['operation_date'])
    print(body['transaction']['description'])
    print(body['transaction']['error_message'])
    print(body['transaction']['order_id'])
    print(body['transaction']['customer_id'])
    print(body['transaction']['amount'])
    print(body['transaction']['currency'])


def chargeSucceeded(body):
    print(body['transaction']['id'])
    print(body['transaction']['authorization'])
    print(body['transaction']['method'])
    print(body['transaction']['operation_type'])
    print(body['transaction']['transaction_type'])
    print(body['transaction']['status'])
    print(body['transaction']['conciliated'])
    print(body['transaction']['creation_date'])
    print(body['transaction']['operation_date'])
    print(body['transaction']['description'])
    print(body['transaction']['error_message'])
    print(body['transaction']['order_id'])
    print(body['transaction']['customer_id'])
    print(body['transaction']['amount'])
    print(body['transaction']['currency'])
